Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-05, with the labels that each got.

#433 The grand reopening Part 3: Add basic DEM
  .typos.toml
  NEWS.md
  README.md
  docs/make.jl
  docs/src/systems/boundary.md
  docs/src/systems/dem.md
  examples/dem/rectangular_tank_2d.jl
  src/TrixiParticles.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/rhs.jl
  src/schemes/boundary/system.jl
  src/schemes/schemes.jl
  src/schemes/solid/discrete_element_method/discrete_element_method.jl
  src/schemes/solid/discrete_element_method/rhs.jl
  src/schemes/solid/discrete_element_method/system.jl
  src/visualization/write2vtk.jl
  test/examples/examples.jl
  test/systems/boundary_system.jl
  test/systems/dem_system.jl
  test/systems/systems.jl
Labels: enhancement, high priority

#492 Recursively convert (adapt) `Semidiscretization` object to GPU types with Adapt.jl
  Project.toml
  src/TrixiParticles.jl
  src/general/gpu.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/monaghan_kajtar/monaghan_kajtar.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
Labels: gpu

#440 Reopen #390: Update callback
  src/TrixiParticles.jl
  src/callbacks/callbacks.jl
  src/callbacks/update.jl
  test/callbacks/callbacks.jl
  test/callbacks/update.jl
Labels: high priority

#527 Create output directory for post process callback if it doesn't exist
  src/callbacks/post_process.jl
Labels: bug

#532 Add type `GPUSystem` to determine if a system is stored on the CPU or GPU
  examples/n_body/n_body_system.jl
  src/general/general.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/schemes/solid/discrete_element_method/system.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  test/general/semidiscretization.jl
Labels: gpu
