Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-07, with the labels that each got.

#561 Release v0.2
  NEWS.md
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/general/neighborhood_search.md
  docs/src/reference-pointneighbors.md
  examples/dem/rectangular_tank_2d.jl
  examples/fluid/dam_break_2d.jl
  examples/fluid/periodic_channel_2d.jl
  examples/n_body/n_body_system.jl
  src/TrixiParticles.jl
  src/general/corrections.jl
  src/general/density_calculators.jl
  src/general/gpu.jl
  src/general/initial_condition.jl
  src/general/interpolation.jl
  src/general/neighborhood_search.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/rhs.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/surface_tension.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/solid/discrete_element_method/rhs.jl
  src/schemes/solid/total_lagrangian_sph/rhs.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  src/util.jl
  test/count_allocations.jl
  test/general/interpolation.jl
  test/general/semidiscretization.jl
  test/schemes/boundary/dummy_particles/dummy_particles.jl
  test/schemes/boundary/dummy_particles/rhs.jl
  test/schemes/boundary/monaghan_kajtar/monaghan_kajtar.jl
  test/schemes/fluid/rhs.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
  test/systems/solid_system.jl
  test/validation/validation.jl
  validation/dam_break_2d/validation_dam_break_2d.jl
  validation/dam_break_2d/validation_reference_edac_0001875.json
  validation/dam_break_2d/validation_reference_edac_00075.json
  validation/dam_break_2d/validation_reference_edac_0015.json
  validation/dam_break_2d/validation_reference_wcsph_0001875.json
  validation/dam_break_2d/validation_reference_wcsph_00075.json
  validation/dam_break_2d/validation_reference_wcsph_0015.json
Labels: breaking changes

#569 Fix viscosity calculation when using two different fluids
  examples/fluid/dam_break_oil_film_2d.jl
  examples/fluid/falling_water_spheres_2d.jl
  src/schemes/boundary/boundary.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/viscosity.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/schemes.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  test/examples/examples.jl
  test/schemes/fluid/viscosity.jl
Labels: bug

#563 GPU-compatible neighborhood search
  src/general/neighborhood_search.jl
  src/general/semidiscretization.jl
Labels: gpu

#578 Inline viscosity
  src/schemes/fluid/viscosity.jl
Labels: performance

#505 Support different systems in Interpolation
  src/general/interpolation.jl
Labels: enhancement

#580 Fix `InitialCondition` in 1D
  src/general/initial_condition.jl
Labels: bug

#579 Make `SolutionSavingCallback` work on GPUs
  src/visualization/write2vtk.jl
Labels: gpu
