Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-06, with the labels that each got.

#542 Precompute git hash to avoid overhead
  src/callbacks/post_process.jl
  src/callbacks/solution_saving.jl
  src/general/file_system.jl
  src/general/general.jl
  src/util.jl
  src/visualization/write2vtk.jl
Labels: performance

#462 Example on how to save interpolated planes using postprocessing callback
  examples/postprocessing/interpolation_plane.jl
Labels: visualization

#442 Add open boundaries
  NEWS.md
  README.md
  docs/src/systems/boundary.md
  examples/fluid/pipe_flow_2d.jl
  examples/n_body/n_body_system.jl
  src/TrixiParticles.jl
  src/callbacks/density_reinit.jl
  src/callbacks/post_process.jl
  src/callbacks/solution_saving.jl
  src/callbacks/update.jl
  src/general/buffer.jl
  src/general/density_calculators.jl
  src/general/general.jl
  src/general/semidiscretization.jl
  src/general/system.jl
  src/schemes/boundary/open_boundary/boundary_zones.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/rhs.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/viscosity.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/schemes/schemes.jl
  src/schemes/solid/discrete_element_method/system.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  src/setups/extrude_geometry.jl
  src/visualization/recipes_plots.jl
  src/visualization/write2vtk.jl
  test/examples/examples.jl
  test/general/buffer.jl
  test/general/general.jl
  test/general/semidiscretization.jl
  test/schemes/boundary/open_boundary/boundary_zone.jl
  test/schemes/boundary/open_boundary/characteristic_variables.jl
  test/schemes/boundary/open_boundary/open_boundary.jl
  test/schemes/schemes.jl
  test/systems/open_boundary_system.jl
  test/systems/systems.jl
Labels: high priority

#534 Rewrite `@threaded` macro to work with GPUs
  Project.toml
  examples/fluid/dam_break_2d.jl
  examples/n_body/n_body_system.jl
  src/TrixiParticles.jl
  src/general/corrections.jl
  src/general/general.jl
  src/general/gpu.jl
  src/general/neighborhood_search.jl
  src/general/semidiscretization.jl
  src/general/system.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  src/util.jl
  test/count_allocations.jl
  test/examples/examples.jl
  test/general/semidiscretization.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
Labels: gpu

#554 Fix function name
  src/schemes/boundary/open_boundary/system.jl
Labels: bug

#550 Use new v0.3 release of PointNeighbors.jl
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/general/neighborhood_search.md
  docs/src/reference-pointneighbors.md
  examples/dem/rectangular_tank_2d.jl
  examples/fluid/dam_break_2d.jl
  examples/fluid/periodic_channel_2d.jl
  examples/n_body/n_body_system.jl
  src/TrixiParticles.jl
  src/general/corrections.jl
  src/general/density_calculators.jl
  src/general/initial_condition.jl
  src/general/interpolation.jl
  src/general/neighborhood_search.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/rhs.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/surface_tension.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/solid/discrete_element_method/rhs.jl
  src/schemes/solid/total_lagrangian_sph/rhs.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  test/count_allocations.jl
  test/general/interpolation.jl
  test/general/semidiscretization.jl
  test/schemes/boundary/dummy_particles/dummy_particles.jl
  test/schemes/boundary/dummy_particles/rhs.jl
  test/schemes/boundary/monaghan_kajtar/monaghan_kajtar.jl
  test/schemes/fluid/rhs.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
  test/systems/solid_system.jl
  validation/dam_break_2d/validation_dam_break_2d.jl
Labels: breaking changes

#504 Add Viscosity Formulation as per Morris et al.
  examples/fluid/dam_break_2d.jl
  examples/fluid/oscillating_drop_2d.jl
  src/TrixiParticles.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/viscosity.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/solid/total_lagrangian_sph/rhs.jl
  src/visualization/write2vtk.jl
  test/examples/examples.jl
  test/schemes/fluid/fluid.jl
  test/schemes/fluid/viscosity.jl
  test/validation/validation.jl
  validation/dam_break_2d/validation_reference_edac_00075.json
  validation/dam_break_2d/validation_reference_wcsph_0001875.json
  validation/dam_break_2d/validation_reference_wcsph_00075.json
  validation/dam_break_2d/validation_reference_wcsph_0015.json
Labels: enhancement
