Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-11, with the labels that each got.

#659 Fix image path
  docs/src/visualization.md
Labels: high priority

#663 Fix installation instructions for developers in the docs
  README.md
  docs/src/install.md
Labels: bug, documentation

#664 Test docs on win
  .github/workflows/Documenter.yml
  docs/make.jl
Labels: bug, high priority

#660 Add docs for GPU support
  docs/make.jl
  docs/src/gpu.md
  docs/src/overview.md
  docs/src/reference-pointneighbors.md
  test/examples/examples.jl
Labels: documentation, high priority, gpu

#658 Clarify statement of need
  README.md
  docs/src/index.md
Labels: high priority

#662 Make simulations run with `Float32`
  src/general/corrections.jl
  src/general/smoothing_kernels.jl
  src/schemes/fluid/viscosity.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  test/general/smoothing_kernels.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
  test/systems/solid_system.jl
Labels: enhancement, performance, gpu

#609 Fixes for Open Boundary Systems for free surfaces
  examples/fluid/pipe_flow_2d.jl
  examples/fluid/pipe_flow_3d.jl
  src/schemes/boundary/open_boundary/boundary_zones.jl
  src/schemes/boundary/open_boundary/method_of_characteristics.jl
  src/schemes/boundary/open_boundary/system.jl
  src/setups/extrude_geometry.jl
  test/examples/examples.jl
  test/schemes/boundary/open_boundary/boundary_zone.jl
Labels: enhancement

#669 Fix callback `show` and remove hacky workaround
  src/callbacks/solution_saving.jl
  test/callbacks/solution_saving.jl
Labels: bug, high priority

#607 Add ideal gas equation
  examples/fluid/dam_break_2phase_2d.jl
  examples/fluid/dam_break_oil_film_2d.jl
  src/TrixiParticles.jl
  src/schemes/fluid/weakly_compressible_sph/state_equations.jl
  src/visualization/write2vtk.jl
  test/examples/examples.jl
  test/schemes/fluid/weakly_compressible_sph/state_equation.jl
Labels: enhancement

#514 Add tutorial for setting up a simulation
  docs/make.jl
  docs/src/examples.md
  docs/src/systems/weakly_compressible_sph.md
  docs/src/tutorials_template/tut_setup.md
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
Labels: documentation
