Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-10, with the labels that each got.

#626 Fix tests for TimerOutputs
  Project.toml
  test/callbacks/info.jl
Labels: high priority

#599 Prepare CI for 1.11 release
  .github/workflows/Invalidations.yml
  .github/workflows/ci.yml
  test/validation/validation.jl
Labels: high priority

#631 Fix getting started docs
  docs/Project.toml
  docs/src/getting_started.md
Labels: bug, documentation

#632 Fix plotting of `ODESolution`
  Project.toml
  src/visualization/recipes_plots.jl
Labels: bug, visualization

#436 Reopen #221: Transport Velocity for EDAC
  NEWS.md
  Project.toml
  docs/src/refs.bib
  docs/src/systems/entropically_damped_sph.md
  examples/fluid/lid_driven_cavity_2d.jl
  examples/fluid/periodic_array_of_cylinders_2d.jl
  examples/fluid/taylor_green_vortex_2d.jl
  src/TrixiParticles.jl
  src/callbacks/update.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/transport_velocity.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/setups/rectangular_shape.jl
  src/visualization/write2vtk.jl
  test/examples/examples.jl
  test/schemes/fluid/fluid.jl
  test/schemes/fluid/transport_velocity.jl
  test/systems/edac_system.jl
  validation/lid_driven_cavity_2d/validation_lid_driven_cavity_2d.jl
  validation/taylor_green_vortex_2d/validation_taylor_green_vortex_2d.jl
Labels: enhancement, high priority
