Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-03, with the labels that each got.

#446 Don't cancel all running CI jobs when one job fails
  .github/workflows/ci.yml
Labels: testing

#461 Fix metadata option for TLSPH system
  src/visualization/write2vtk.jl
Labels: bug

#449 Add plots and package installation instruction to docs
  README.md
  docs/src/getting_started.md
  docs/src/index.md
  docs/src/install.md
Labels: documentation

#465 Add missing semicolon for kwarg
  src/callbacks/callbacks.jl
Labels: bug, high priority

#468 Replace externally hosted density diffusion images in docs
  docs/src/systems/weakly_compressible_sph.md
Labels: documentation

#431 The grand reopening Part 1: Validation setup for dam break
  examples/fluid/dam_break_2d.jl
  src/TrixiParticles.jl
  src/callbacks/solution_saving.jl
  src/general/interpolation.jl
  src/general/semidiscretization.jl
  src/schemes/fluid/fluid.jl
  test/examples/examples.jl
  test/validation/validation.jl
  validation/dam_break_2d/README.md
  validation/dam_break_2d/exp_pressure_sensor_P1.csv
  validation/dam_break_2d/exp_pressure_sensor_P2.csv
  validation/dam_break_2d/exp_surge_front.csv
  validation/dam_break_2d/plot_dam_break_results.jl
  validation/dam_break_2d/sim_pressure_sensor_P1.csv
  validation/dam_break_2d/sim_pressure_sensor_P2.csv
  validation/dam_break_2d/validation_dam_break_2d.jl
  validation/dam_break_2d/validation_reference_edac_0001875.json
  validation/dam_break_2d/validation_reference_edac_00075.json
  validation/dam_break_2d/validation_reference_edac_0015.json
  validation/dam_break_2d/validation_reference_wcsph_0001875.json
  validation/dam_break_2d/validation_reference_wcsph_00075.json
  validation/dam_break_2d/validation_reference_wcsph_0015.json
  validation/oscillating_beam_2d/validation_oscillating_beam_2d.jl
  validation/validation_util.jl
Labels: testing, high priority

#432 The grand reopening Part 2: Add overview page
  docs/make.jl
  docs/src/development.md
  docs/src/examples.md
  docs/src/index.md
  docs/src/install.md
  docs/src/overview.md
  examples/fluid/periodic_channel_2d.jl
  examples/fsi/dam_break_plate_2d.jl
  examples/fsi/falling_sphere_2d.jl
  examples/fsi/falling_sphere_3d.jl
  examples/fsi/falling_spheres_2d.jl
  src/general/file_system.jl
  test/examples/examples.jl
Labels: documentation, high priority
