Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-09, with the labels that each got.

#606 Skip empty systems
  src/visualization/write2vtk.jl
Labels: bug

#614 Add YouTube video of JuliaCon talk to README
  README.md
Labels: documentation

#608 Artificial Density Diffusion should only be applied to the same system
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
Labels: bug

#605 Remove soundspeed from openboundary system
  examples/fluid/pipe_flow_2d.jl
  src/schemes/boundary/open_boundary/method_of_characteristics.jl
  src/schemes/boundary/open_boundary/system.jl
  src/visualization/write2vtk.jl
  test/general/buffer.jl
  test/schemes/boundary/open_boundary/characteristic_variables.jl
  test/systems/open_boundary_system.jl
Labels: enhancement

#610 Remove unsafe bitsets
  src/general/buffer.jl
  src/preprocessing/geometries/triangle_mesh.jl
  src/schemes/boundary/open_boundary/boundary_zones.jl
Labels: bug, high priority

#603 Fix moving boundaries
  examples/fluid/accelerated_tank_2d.jl
  src/schemes/boundary/system.jl
Labels: bug

#621 Fix sign in `OutFlow`
  src/schemes/boundary/open_boundary/boundary_zones.jl
Labels: bug
