Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2024-04, with the labels that each got.

#489 Fix another closures error on macOS-ARM
  src/schemes/solid/total_lagrangian_sph/system.jl
Labels: bug

#437 Reopen #382: Extrude shapes/geometry
  src/TrixiParticles.jl
  src/general/interpolation.jl
  src/setups/extrude_geometry.jl
  src/setups/rectangular_shape.jl
  src/setups/setups.jl
  test/setups/extrude_geometry.jl
  test/setups/setups.jl
Labels: high priority

#475 Optimization bnd pressure computation
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  test/validation/validation.jl
  validation/dam_break_2d/validation_reference_edac_0015.json
  validation/dam_break_2d/validation_reference_wcsph_0015.json
Labels: high priority, performance

#485 Add `show` for `SolutionSavingCallback` with `save_times`
  src/callbacks/post_process.jl
  src/callbacks/solution_saving.jl
  test/callbacks/callbacks.jl
  test/callbacks/solution_saving.jl
Labels: bug
