Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2025-04, with the labels that each got.

#740 Fix FSI-Open Boundary interaction and add variable material parameters
  src/general/semidiscretization.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/solid/total_lagrangian_sph/penalty_force.jl
  src/schemes/solid/total_lagrangian_sph/rhs.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  src/visualization/write2vtk.jl
  test/systems/solid_system.jl
Labels: bug, enhancement

#752 Fix missed `@threaded semi`
  src/schemes/boundary/open_boundary/mirroring.jl
  src/schemes/fluid/surface_tension.jl
Labels: bug

#600 Transport Velocity Formulation for WCSPH
  examples/fluid/lid_driven_cavity_2d.jl
  examples/fluid/taylor_green_vortex_2d.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/transport_velocity.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  test/examples/examples_fluid.jl
  test/systems/wcsph_system.jl
  validation/lid_driven_cavity_2d/validation_lid_driven_cavity_2d.jl
  validation/taylor_green_vortex_2d/validation_taylor_green_vortex_2d.jl
Labels: bug

#735 Implement the Particle Shifting Technique (PST)
  src/TrixiParticles.jl
  src/callbacks/callbacks.jl
  src/callbacks/particle_shifting.jl
  src/general/system.jl
  src/schemes/fluid/fluid.jl
  src/visualization/recipes_plots.jl
  src/visualization/write2vtk.jl
Labels: enhancement

#761 Consider `DensityDiffusionAntuono` in `allocate_buffer`
  src/general/buffer.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
Labels: bug

#765 Suppress iteration over inactive particles
  src/callbacks/particle_shifting.jl
Labels: bug

#755 Rework custom quantities
  examples/postprocessing/interpolation_plane.jl
  examples/postprocessing/postprocessing.jl
  examples/solid/oscillating_beam_2d.jl
  src/TrixiParticles.jl
  src/callbacks/particle_shifting.jl
  src/callbacks/post_process.jl
  src/callbacks/solution_saving.jl
  src/callbacks/steady_state_reached.jl
  src/general/corrections.jl
  src/general/custom_quantities.jl
  src/general/density_calculators.jl
  src/general/interpolation.jl
  src/general/semidiscretization.jl
  src/general/system.jl
  src/preprocessing/particle_packing/system.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/monaghan_kajtar/monaghan_kajtar.jl
  src/schemes/boundary/open_boundary/method_of_characteristics.jl
  src/schemes/boundary/open_boundary/mirroring.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/rhs.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/surface_normal_sph.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/schemes/solid/discrete_element_method/system.jl
  src/schemes/solid/total_lagrangian_sph/rhs.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  src/visualization/write2vtk.jl
  test/callbacks/postprocess.jl
  test/callbacks/solution_saving.jl
  test/general/semidiscretization.jl
  test/schemes/boundary/dummy_particles/rhs.jl
  validation/dam_break_2d/validation_dam_break_2d.jl
  validation/taylor_green_vortex_2d/validation_taylor_green_vortex_2d.jl
Labels: enhancement, breaking changes

#776 Hotfix for unit tests
  test/schemes/solid/total_lagrangian_sph/rhs.jl
Labels: bug, testing, high priority

#581 Make Adami loop flipping optimization optional
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  validation/dam_break_2d/validation_dam_break_2d.jl
  validation/dam_break_2d/validation_reference_edac_0015.json
  validation/dam_break_2d/validation_reference_wcsph_0015.json
Labels: enhancement

#725 Viscosity Doc Refactoring
  docs/src/refs.bib
  docs/src/systems/fluid.md
  docs/src/tutorials_template/tut_setup.md
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/viscosity.jl
  test/schemes/fluid/surface_normal_sph.jl
Labels: documentation

#779 Visualization doc: How to scale point size in ParaView
  docs/src/visualization.md
Labels: documentation
