Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2025-07, with the labels that each got.

#819 Clean up timer outputs
  src/TrixiParticles.jl
  src/callbacks/particle_shifting.jl
  src/callbacks/post_process.jl
  src/io/write_vtk.jl
Labels: enhancement

#839 Remove duplicate pressure limiting for Adami BC
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/system.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
Labels: performance

#815 Add descriptive header to each example
  examples/dem/collapsing_sand_pile_3d.jl
  examples/dem/rectangular_tank_2d.jl
  examples/fluid/accelerated_tank_2d.jl
  examples/fluid/dam_break_2d.jl
  examples/fluid/dam_break_2d_gpu.jl
  examples/fluid/dam_break_2phase_2d.jl
  examples/fluid/dam_break_3d.jl
  examples/fluid/dam_break_oil_film_2d.jl
  examples/fluid/falling_water_column_2d.jl
  examples/fluid/falling_water_spheres_2d.jl
  examples/fluid/falling_water_spheres_3d.jl
  examples/fluid/hydrostatic_water_column_2d.jl
  examples/fluid/hydrostatic_water_column_3d.jl
  examples/fluid/lid_driven_cavity_2d.jl
  examples/fluid/moving_wall_2d.jl
  examples/fluid/oscillating_drop_2d.jl
  examples/fluid/periodic_array_of_cylinders_2d.jl
  examples/fluid/periodic_channel_2d.jl
  examples/fluid/pipe_flow_2d.jl
  examples/fluid/pipe_flow_3d.jl
  examples/fluid/sphere_surface_tension_2d.jl
  examples/fluid/sphere_surface_tension_3d.jl
  examples/fluid/sphere_surface_tension_wall_2d.jl
  examples/fluid/taylor_green_vortex_2d.jl
  examples/fsi/dam_break_gate_2d.jl
  examples/fsi/dam_break_plate_2d.jl
  examples/fsi/falling_sphere_2d.jl
  examples/fsi/falling_sphere_3d.jl
  examples/fsi/falling_spheres_2d.jl
  examples/fsi/falling_water_column_2d.jl
  examples/n_body/n_body_benchmark_reference.jl
  examples/n_body/n_body_benchmark_reference_faster.jl
  examples/n_body/n_body_benchmark_trixi.jl
  examples/n_body/n_body_solar_system.jl
  examples/postprocessing/interpolation_plane.jl
  examples/postprocessing/interpolation_point_line.jl
  examples/postprocessing/postprocessing.jl
  examples/preprocessing/complex_shape_2d.jl
  examples/preprocessing/complex_shape_3d.jl
  examples/preprocessing/packing_2d.jl
  examples/preprocessing/packing_3d.jl
  examples/solid/oscillating_beam_2d.jl
Labels: documentation

#849 Avoid `atomic_cas` in open boundaries and add gpu tests
  src/general/buffer.jl
  src/general/semidiscretization.jl
  src/schemes/boundary/open_boundary/system.jl
  test/examples/gpu.jl
  test/general/buffer.jl
  test/systems/open_boundary_system.jl
Labels: gpu

#862 Improve plot recipes
  src/visualization/recipes_plots.jl
Labels: enhancement, visualization

#853 Fix Adami boundary viscosity
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  test/schemes/boundary/dummy_particles/dummy_particles.jl
Labels: bug

#834 Make PST work for different smoothing length factors
  src/callbacks/particle_shifting.jl
Labels: bug
