Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2025-01, with the labels that each got.

#636 Add set operations for geometries
  examples/preprocessing/data/cube.stl
  examples/preprocessing/data/polyhedron.stl
  examples/preprocessing/data/sphere.stl
  src/general/initial_condition.jl
  src/preprocessing/point_in_poly/winding_number_jacobson.jl
  src/setups/complex_shape.jl
  test/preprocessing/data/coordinates_sphere.csv
  test/preprocessing/data/normals_sphere.csv
  test/preprocessing/geometries/geometries.jl
  test/setups/complex_shape.jl
Labels: enhancement

#696 Make `load_geometry` type stable
  src/preprocessing/geometries/io.jl
Labels: enhancement, performance

#684 Use Asciicast.jl to display console output
  docs/Project.toml
  docs/make.jl
  docs/src/tutorials_template/tut_setup.md
Labels: documentation

#529 Particle packing
  NEWS.md
  Project.toml
  docs/src/preprocessing/preprocessing.md
  examples/preprocessing/complex_shape_2d.jl
  examples/preprocessing/complex_shape_3d.jl
  examples/preprocessing/packing_2d.jl
  examples/preprocessing/packing_3d.jl
  src/TrixiParticles.jl
  src/callbacks/update.jl
  src/general/custom_quantities.jl
  src/general/initial_condition.jl
  src/preprocessing/geometries/geometries.jl
  src/preprocessing/geometries/io.jl
  src/preprocessing/geometries/polygon.jl
  src/preprocessing/geometries/triangle_mesh.jl
  src/preprocessing/particle_packing/nhs_faces.jl
  src/preprocessing/particle_packing/particle_packing.jl
  src/preprocessing/particle_packing/rhs.jl
  src/preprocessing/particle_packing/signed_distance.jl
  src/preprocessing/particle_packing/system.jl
  src/preprocessing/point_in_poly/winding_number_hormann.jl
  src/preprocessing/point_in_poly/winding_number_jacobson.jl
  src/preprocessing/preprocessing.jl
  src/schemes/fluid/transport_velocity.jl
  src/setups/complex_shape.jl
  test/examples/examples.jl
  test/preprocessing/data/signed_distances_circle.csv
  test/preprocessing/data/signed_distances_hexagon.csv
  test/preprocessing/data/signed_distances_sphere.csv
  test/preprocessing/packing/nhs_faces.jl
  test/preprocessing/packing/packing.jl
  test/preprocessing/packing/signed_distance.jl
  test/preprocessing/preprocessing.jl
Labels: enhancement, high priority

#710 Docs tutorial: add more information on the speed of sound
  docs/src/tutorials_template/tut_setup.md
Labels: documentation

#539 Generalize surface normal calc
  NEWS.md
  Project.toml
  docs/make.jl
  docs/src/systems/fluid.md
  docs/src/systems/weakly_compressible_sph.md
  examples/fluid/dam_break_2d.jl
  examples/fluid/dam_break_oil_film_2d.jl
  examples/fluid/falling_water_spheres_2d.jl
  examples/fluid/falling_water_spheres_3d.jl
  examples/fluid/sphere_surface_tension_2d.jl
  examples/fluid/sphere_surface_tension_3d.jl
  examples/fluid/sphere_surface_tension_wall_2d.jl
  src/TrixiParticles.jl
  src/schemes/boundary/boundary.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/entropically_damped_sph/rhs.jl
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/fluid/surface_normal_sph.jl
  src/schemes/fluid/surface_tension.jl
  src/schemes/fluid/weakly_compressible_sph/rhs.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  src/visualization/write2vtk.jl
  test/schemes/fluid/fluid.jl
  test/schemes/fluid/surface_normal_sph.jl
  test/systems/edac_system.jl
  test/systems/wcsph_system.jl
Labels: enhancement
