Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2025-05, with the labels that each got.

#790 Add full support for parallelization backends
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/gpu.md
  examples/fluid/dam_break_2d.jl
  examples/fluid/dam_break_2d_gpu.jl
  examples/fluid/dam_break_2phase_2d.jl
  examples/fluid/dam_break_3d.jl
  examples/fluid/dam_break_oil_film_2d.jl
  examples/fluid/hydrostatic_water_column_2d.jl
  examples/fluid/periodic_channel_2d.jl
  examples/fluid/pipe_flow_2d.jl
  examples/fsi/dam_break_gate_2d.jl
  examples/n_body/n_body_system.jl
  examples/solid/oscillating_beam_2d.jl
  src/TrixiParticles.jl
  src/general/initial_condition.jl
  src/general/neighborhood_search.jl
  src/general/semidiscretization.jl
  src/preprocessing/geometries/triangle_mesh.jl
  src/preprocessing/particle_packing/signed_distance.jl
  src/preprocessing/point_in_poly/winding_number_hormann.jl
  src/preprocessing/point_in_poly/winding_number_jacobson.jl
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  test/count_allocations.jl
  test/examples/examples_fluid.jl
  test/schemes/fluid/surface_tension.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
  test/systems/boundary_system.jl
  test/test_util.jl
Labels: breaking changes

#756 DEM improvements
  NEWS.md
  Project.toml
  docs/src/systems/dem.md
  examples/dem/collapsing_sand_pile_3d.jl
  examples/dem/rectangular_tank_2d.jl
  src/TrixiParticles.jl
  src/io/write_vtk.jl
  src/schemes/boundary/system.jl
  src/schemes/solid/discrete_element_method/contact_models.jl
  src/schemes/solid/discrete_element_method/discrete_element_method.jl
  src/schemes/solid/discrete_element_method/rhs.jl
  src/schemes/solid/discrete_element_method/system.jl
  test/examples/examples.jl
  test/systems/dem_system.jl
Labels: bug, enhancement, breaking changes

#763 Improve plane interpolation performance
  examples/postprocessing/interpolation_plane.jl
  examples/postprocessing/interpolation_point_line.jl
  src/TrixiParticles.jl
  src/general/interpolation.jl
  test/examples/examples.jl
  test/general/interpolation.jl
Labels: performance

#809 Fix allocations caused by branching with 1.10
  src/schemes/boundary/dummy_particles/dummy_particles.jl
  test/schemes/boundary/dummy_particles/dummy_particles.jl
Labels: bug

#722 Implement threaded broadcast array type to make time integration multithreaded
  NEWS.md
  src/general/semidiscretization.jl
  src/util.jl
  test/count_allocations.jl
  test/general/general.jl
  test/general/util.jl
  test/schemes/solid/total_lagrangian_sph/rhs.jl
Labels: performance

#769 Implement Tensile Instability Control (TIC)
  docs/src/refs.bib
  docs/src/systems/fluid.md
  docs/src/systems/weakly_compressible_sph.md
  examples/fluid/periodic_channel_2d.jl
  src/TrixiParticles.jl
  src/callbacks/particle_shifting.jl
  src/schemes/fluid/pressure_acceleration.jl
  src/schemes/fluid/weakly_compressible_sph/density_diffusion.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
  test/examples/examples_fluid.jl
Labels: enhancement

#797 Add docs particle packing
  docs/src/preprocessing/preprocessing.md
  docs/src/refs.bib
  src/preprocessing/particle_packing/system.jl
Labels: documentation

#807 Fix error message when using TVF without UpdateCB
  src/schemes/fluid/entropically_damped_sph/system.jl
  src/schemes/fluid/transport_velocity.jl
  src/schemes/fluid/weakly_compressible_sph/system.jl
Labels: bug
