Repository trixi-framework/TrixiParticles.jl, pull requests merged in 2025-09, with the labels that each got.

#891 Incorrect Smoothing Length
  examples/fluid/dam_break_2phase_2d.jl
  examples/fluid/dam_break_oil_film_2d.jl
  test/schemes/boundary/dummy_particles/dummy_particles.jl
Labels: bug

#879 Add `dvdu_ode` vector to `custom_quantities`
  examples/postprocessing/interpolation_plane.jl
  examples/postprocessing/postprocessing.jl
  src/TrixiParticles.jl
  src/callbacks/post_process.jl
  src/callbacks/solution_saving.jl
  src/callbacks/steady_state_reached.jl
  src/general/custom_quantities.jl
  src/io/write_vtk.jl
  src/schemes/boundary/open_boundary/system.jl
  src/schemes/boundary/system.jl
  src/schemes/fluid/fluid.jl
  src/schemes/solid/discrete_element_method/system.jl
  src/schemes/solid/total_lagrangian_sph/system.jl
  test/callbacks/solution_saving.jl
  test/general/custom_quantities.jl
  test/io/read_vtk.jl
  validation/dam_break_2d/validation_dam_break_2d.jl
  validation/lid_driven_cavity_2d/validation_lid_driven_cavity_2d.jl
  validation/taylor_green_vortex_2d/validation_taylor_green_vortex_2d.jl
Labels: enhancement, breaking changes

#909 Make `PrescribedMotion` more powerful by passing the initial position
  NEWS.md
  examples/fluid/accelerated_tank_2d.jl
  examples/fluid/lid_driven_cavity_2d.jl
  examples/fluid/moving_wall_2d.jl
  examples/fsi/dam_break_gate_2d.jl
  src/schemes/boundary/prescribed_motion.jl
  src/schemes/boundary/wall_boundary/system.jl
  test/systems/boundary_system.jl
Labels: breaking changes

#597 Define boundary zone from STL-file
  NEWS.md
  Project.toml
  docs/src/systems/boundary.md
  examples/fluid/pipe_flow_2d.jl
  examples/fluid/pipe_flow_3d.jl
  src/TrixiParticles.jl
  src/io/io.jl
  src/preprocessing/geometries/geometries.jl
  src/schemes/boundary/open_boundary/boundary_zones.jl
  src/schemes/boundary/open_boundary/method_of_characteristics.jl
  src/schemes/boundary/open_boundary/mirroring.jl
  src/schemes/boundary/open_boundary/system.jl
  test/general/buffer.jl
  test/preprocessing/data/inflow.stl
  test/preprocessing/data/inflow_geometry.stl
  test/preprocessing/geometries/geometries.jl
  test/schemes/boundary/open_boundary/boundary_zone.jl
  test/schemes/boundary/open_boundary/characteristic_variables.jl
  test/schemes/boundary/open_boundary/mirroring.jl
  test/systems/open_boundary_system.jl
Labels: enhancement, breaking changes

#912 Fix GPU tests, GPU interpolation and GPU postprocessing
  src/callbacks/post_process.jl
  src/general/interpolation.jl
  src/io/io.jl
  src/io/write_vtk.jl
  test/examples/gpu.jl
Labels: bug

#921 Fix `eltype` in `compact_support`
  src/general/semidiscretization.jl
Labels: bug

#751 Implement Implicit Incompressible SPH (IISPH)
  NEWS.md
  docs/make.jl
  docs/src/refs.bib
  docs/src/systems/implicit_incompressible_sph.md
  examples/fluid/dam_break_2d.jl
  examples/fluid/dam_break_2d_iisph.jl
  ext/TrixiParticlesOrdinaryDiffEqExt.jl
  src/TrixiParticles.jl
  src/general/semidiscretization.jl
  src/io/io.jl
  src/schemes/fluid/implicit_incompressible_sph/implicit_incompressible_sph.jl
  src/schemes/fluid/implicit_incompressible_sph/rhs.jl
  src/schemes/fluid/implicit_incompressible_sph/system.jl
  src/schemes/schemes.jl
  test/examples/examples_fluid.jl
  test/schemes/fluid/rhs.jl
  test/systems/iisph_system.jl
Labels: enhancement

#917 Update program flow diagram (and use Mermaid.js to make it easy to modify)
  docs/Project.toml
  docs/make.jl
  docs/src/overview.md
Labels: documentation
